#if !defined(__LAYOUT_DVORAK_PROGRAMMER_H_)
#define __LAYOUT_DVORAK_PROGRAMMER_H_

#include "keys.h"

const KeySpec dvorakProgrammerKeymap[] = {
/* A               =>  aA */         (KeySpec) { 0, _A, RShift, _A },
/* B               =>  xX */         (KeySpec) { 0, _X, RShift, _X },
/* C               =>  jJ */         (KeySpec) { 0, _J, RShift, _J },
/* D               =>  eE */         (KeySpec) { 0, _E, RShift, _E },
/* E               =>  .> */         (KeySpec) { 0, _Fullstop, RShift, _Fullstop },
/* F               =>  uU */         (KeySpec) { 0, _U, RShift, _U },
/* G               =>  iI */         (KeySpec) { 0, _I, RShift, _I },
/* H               =>  dD */         (KeySpec) { 0, _D, LShift, _D },
/* I               =>  cC */         (KeySpec) { 0, _C, LShift, _C },
/* J               =>  hH */         (KeySpec) { 0, _H, LShift, _H },
/* K               =>  tT */         (KeySpec) { 0, _T, LShift, _T },
/* L               =>  nN */         (KeySpec) { 0, _N, LShift, _N },
/* M               =>  mM */         (KeySpec) { 0, _M, LShift, _M },
/* N               =>  bB */         (KeySpec) { 0, _B, LShift, _B },
/* O               =>  rR */         (KeySpec) { 0, _R, LShift, _R },
/* P               =>  lL */         (KeySpec) { 0, _L, LShift, _L },
/* Q               =>  ;: */         (KeySpec) { 0, _Semicolon, RShift, _Semicolon },
/* R               =>  pP */         (KeySpec) { 0, _P, RShift, _P },
/* S               =>  oO */         (KeySpec) { 0, _O, RShift, _O },
/* T               =>  yY */         (KeySpec) { 0, _Y, RShift, _Y },
/* U               =>  gG */         (KeySpec) { 0, _G, LShift, _G },
/* V               =>  kK */         (KeySpec) { 0, _K, RShift, _K },
/* W               =>  ,< */         (KeySpec) { 0, _Comma, RShift, _Comma },
/* X               =>  qQ */         (KeySpec) { 0, _Q, RShift, _Q },
/* Y               =>  fF */         (KeySpec) { 0, _F, LShift, _F },
/* Z               =>  '" */         (KeySpec) { 0, _Apostrophe, RShift, _Apostrophe },
/* 1               =>  &% */         (KeySpec) { LShift, _7, RShift, _5 },
/* 2               =>  [7 */         (KeySpec) { 0, _LeftBracket, 0, _7 },
/* 3               =>  {5 */         (KeySpec) { LShift, _LeftBracket, 0, _5 },
/* 4               =>  }3 */         (KeySpec) { LShift, _RightBracket, 0, _3 },
/* 5               =>  (1 */         (KeySpec) { LShift, _9, 0, _1 },
/* 6               =>  =9 */         (KeySpec) { 0, _Equals, 0, _9 },
/* 7               =>  *0 */         (KeySpec) { LShift, _8, 0, _0 },
/* 8               =>  )2 */         (KeySpec) { LShift, _0, 0, _2 },
/* 9               =>  +4 */         (KeySpec) { LShift, _Equals, 0, _4 },
/* 0               =>  ]6 */         (KeySpec) { 0, _RightBracket, 0, _6 },
/* Enter           =>  Enter */      (KeySpec) { 0, _Enter, LShift, _Enter },
/* Escape          =>  Escape */     (KeySpec) { 0, _Escape, RShift, _Escape },
/* Backspace       =>  Backspace */  (KeySpec) { 0, _Backspace, LShift, _Backspace },
/* Tab             =>  Tab */        (KeySpec) { 0, _Tab, RShift, _Tab },
/* Space           =>  Space */      (KeySpec) { 0, _Space, LShift, _Space },
/* Dash            =>  !8 */         (KeySpec) { RShift, _1, 0, _8 },
/* Equals          =>  #` */         (KeySpec) { RShift, _3, 0, _Backtick },
/* LeftBracket     =>  /? */         (KeySpec) { 0, _ForwardSlash, LShift, _ForwardSlash },
/* RightBracket    =>  @^ */         (KeySpec) { RShift, _2, RShift, _6 },
/* Backslash       =>  \| */         (KeySpec) { 0, _Backslash, LShift, _Backslash },
/* International2  =>  ... */        (KeySpec) { 0, _International2, LShift, _International2 },
/* Semicolon       =>  sS */         (KeySpec) { 0, _S, LShift, _S },
/* Apostrophe      =>  -_ */         (KeySpec) { 0, _Dash, LShift, _Dash },
/* Backtick        =>  $~ */         (KeySpec) { RShift, _4, RShift, _Backtick },
/* Comma           =>  wW */         (KeySpec) { 0, _W, LShift, _W },
/* Fullstop        =>  vV */         (KeySpec) { 0, _V, LShift, _V },
/* ForwardSlash    =>  zZ */         (KeySpec) { 0, _Z, LShift, _Z },
/* CapsLock        =>  Capslock */   (KeySpec) { 0, _CapsLock, RShift, _CapsLock }
};

#endif // __LAYOUT_DVORAK_PROGRAMMER_H_
